/* eslint-disable sonarjs/no-duplicate-string */
// Keep duplicate country names in different lists

export const fallbackIntlMastercardFirst = {
  country: "United States",
  countryCode: "US",
  name: "Mastercard Prepaid USD Debit (Virtual only) US",
  sku: 18732,
};

export const fallbackIntlMastercardSecond = {
  country: "United States",
  countryCode: "US",
  name: "Virtual MasterCard International USD US",
  sku: 18597,
};

export const fallbackIntlVisa = {
  country: "United States",
  countryCode: "US",
  name: "Visa International USD (Virtual) US",
  sku: 18598,
};

export const masterCardIntlSkus = [
  {
    country: "United States",
    countryCode: "US",
    name: "Mastercard Prepaid USD Debit (Virtual only) US",
    sku: 18732,
  },
  {
    country: "United States",
    countryCode: "US",
    name: "Virtual MasterCard International USD US",
    sku: 18597,
  },
  {
    country: "Algeria",
    countryCode: "DZ",
    name: "Mastercard Prepaid USD Debit (Virtual only) DZ",
    sku: 18630,
  },
  {
    country: "Australia",
    countryCode: "AU",
    name: "Mastercard Prepaid USD Debit (Virtual only) AU",
    sku: 18631,
  },
  {
    country: "Austria",
    countryCode: "AT",
    name: "Mastercard Prepaid USD Debit (Virtual only) AT",
    sku: 18632,
  },
  {
    country: "Bangladesh",
    countryCode: "BD",
    name: "Mastercard Prepaid USD Debit (Virtual only) BD",
    sku: 18633,
  },
  {
    country: "Belgium",
    countryCode: "BE",
    name: "Mastercard Prepaid USD Debit (Virtual only) BE",
    sku: 18634,
  },
  {
    country: "Brazil",
    countryCode: "BR",
    name: "Mastercard Prepaid USD Debit (Virtual only) BR",
    sku: 18635,
  },
  {
    country: "Canada",
    countryCode: "CA",
    name: "Mastercard Prepaid USD Debit (Virtual only) CA",
    sku: 18636,
  },
  {
    country: "Colombia",
    countryCode: "CO",
    name: "Mastercard Prepaid USD Debit (Virtual only) CO",
    sku: 18637,
  },
  {
    country: "Dominica",
    countryCode: "DM",
    name: "Mastercard Prepaid USD Debit (Virtual only) DM",
    sku: 18638,
  },
  {
    country: "Ecuador",
    countryCode: "EC",
    name: "Mastercard Prepaid USD Debit (Virtual only) EC",
    sku: 18639,
  },
  {
    country: "Egypt",
    countryCode: "EG",
    name: "Mastercard Prepaid USD Debit (Virtual only) EG",
    sku: 18640,
  },
  {
    country: "Finland",
    countryCode: "FI",
    name: "Mastercard Prepaid USD Debit (Virtual only) FI",
    sku: 18641,
  },
  {
    country: "France",
    countryCode: "FR",
    name: "Mastercard Prepaid USD Debit (Virtual only) FR",
    sku: 18642,
  },
  {
    country: "Germany",
    countryCode: "DE",
    name: "Mastercard Prepaid USD Debit (Virtual only) DE",
    sku: 18643,
  },
  {
    country: "Greece",
    countryCode: "GR",
    name: "Mastercard Prepaid USD Debit (Virtual only) GR",
    sku: 18644,
  },
  {
    country: "India",
    countryCode: "IN",
    name: "Mastercard Prepaid USD Debit (Virtual only) IN",
    sku: 18645,
  },
  {
    country: "Indonesia",
    countryCode: "ID",
    name: "Mastercard Prepaid USD Debit (Virtual only) ID",
    sku: 18646,
  },
  {
    country: "Ireland",
    countryCode: "IE",
    name: "Mastercard Prepaid USD Debit (Virtual only) IE",
    sku: 18647,
  },
  {
    country: "Italy",
    countryCode: "IT",
    name: "Mastercard Prepaid USD Debit (Virtual only) IT",
    sku: 18648,
  },
  {
    country: "Jamaica",
    countryCode: "JM",
    name: "Mastercard Prepaid USD Debit (Virtual only) JM",
    sku: 18649,
  },
  {
    country: "Jordan",
    countryCode: "JO",
    name: "Mastercard Prepaid USD Debit (Virtual only) JO",
    sku: 18650,
  },
  {
    country: "Malaysia",
    countryCode: "MY",
    name: "Mastercard Prepaid USD Debit (Virtual only) MY",
    sku: 18651,
  },
  {
    country: "Mexico",
    countryCode: "MX",
    name: "Mastercard Prepaid USD Debit (Virtual only) MX",
    sku: 18652,
  },
  {
    country: "Netherlands",
    countryCode: "NL",
    name: "Mastercard Prepaid USD Debit (Virtual only) NL",
    sku: 18653,
  },
  {
    country: "Philippines",
    countryCode: "PH",
    name: "Mastercard Prepaid USD Debit (Virtual only) PH",
    sku: 18654,
  },
  {
    country: "Poland",
    countryCode: "PL",
    name: "Mastercard Prepaid USD Debit (Virtual only) PL",
    sku: 18655,
  },
  {
    country: "Portugal",
    countryCode: "PT",
    name: "Mastercard Prepaid USD Debit (Virtual only) PT",
    sku: 18656,
  },
  {
    country: "Qatar",
    countryCode: "QA",
    name: "Mastercard Prepaid USD Debit (Virtual only) QA",
    sku: 18657,
  },
  {
    country: "Saudi Arabia",
    countryCode: "SA",
    name: "Mastercard Prepaid USD Debit (Virtual only) SA",
    sku: 18658,
  },
  {
    country: "Singapore",
    countryCode: "SG",
    name: "Mastercard Prepaid USD Debit (Virtual only) SG",
    sku: 18659,
  },
  {
    country: "Spain",
    countryCode: "ES",
    name: "Mastercard Prepaid USD Debit (Virtual only) ES",
    sku: 18660,
  },
  {
    country: "Thailand",
    countryCode: "TH",
    name: "Mastercard Prepaid USD Debit (Virtual only) TH",
    sku: 18661,
  },
  {
    country: "United Arab Emirates",
    countryCode: "AE",
    name: "Mastercard Prepaid USD Debit (Virtual only) AE",
    sku: 18662,
  },
  {
    country: "United Kingdom",
    countryCode: "GB",
    name: "Mastercard Prepaid USD Debit (Virtual only) GB",
    sku: 18663,
  },
  {
    country: "United Arab Emirates",
    countryCode: "AE",
    name: "Mastercard Prepaid USD Debit (Virtual only) AE",
    sku: 18674,
  },
];

export const visaIntlSkus = [
  {
    country: "United States",
    countryCode: "US",
    name: "Visa International USD (Virtual) US",
    sku: 18598,
  },
  {
    country: "Algeria",
    countryCode: "DZ",
    name: "Virtual Promotional Prepaid Visa USD DZ",
    sku: 18601,
  },
  {
    country: "Australia",
    countryCode: "AU",
    name: "Virtual Promotional Prepaid Visa USD AU",
    sku: 18602,
  },
  {
    country: "Bangladesh",
    countryCode: "BD",
    name: "Virtual Promotional Prepaid Visa USD BD",
    sku: 18603,
  },
  {
    country: "Belgium",
    countryCode: "BE",
    name: "Virtual Promotional Prepaid Visa USD BE",
    sku: 18604,
  },
  {
    country: "Brazil",
    countryCode: "BR",
    name: "Virtual Promotional Prepaid Visa USD BR",
    sku: 18605,
  },
  {
    country: "Canada",
    countryCode: "CA",
    name: "Virtual Promotional Prepaid Visa USD CA",
    sku: 18606,
  },
  {
    country: "Dominica",
    countryCode: "DM",
    name: "Virtual Promotional Prepaid Visa USD DM",
    sku: 18607,
  },
  {
    country: "Egypt",
    countryCode: "EG",
    name: "Virtual Promotional Prepaid Visa USD EG",
    sku: 18608,
  },
  {
    country: "Finland",
    countryCode: "FI",
    name: "Virtual Promotional Prepaid Visa USD FI",
    sku: 18609,
  },
  {
    country: "France",
    countryCode: "FR",
    name: "Virtual Promotional Prepaid Visa USD FR",
    sku: 18610,
  },
  {
    country: "Georgia",
    countryCode: "GE",
    name: "Virtual Promotional Prepaid Visa USD GE",
    sku: 18611,
  },
  {
    country: "Greece",
    countryCode: "GR",
    name: "Virtual Promotional Prepaid Visa USD GR",
    sku: 18612,
  },
  {
    country: "India",
    countryCode: "IN",
    name: "Virtual Promotional Prepaid Visa USD IN",
    sku: 18613,
  },
  {
    country: "Indonesia",
    countryCode: "ID",
    name: "Virtual Promotional Prepaid Visa USD ID",
    sku: 18614,
  },
  {
    country: "Italy",
    countryCode: "IT",
    name: "Virtual Promotional Prepaid Visa USD IT",
    sku: 18615,
  },
  {
    country: "Jamaica",
    countryCode: "JM",
    name: "Virtual Promotional Prepaid Visa USD JM",
    sku: 18616,
  },
  {
    country: "Jordan",
    countryCode: "JO",
    name: "Virtual Promotional Prepaid Visa USD JO",
    sku: 18617,
  },
  {
    country: "Mexico",
    countryCode: "MX",
    name: "Virtual Promotional Prepaid Visa USD MX",
    sku: 18618,
  },
  {
    country: "Morocco",
    countryCode: "MA",
    name: "Virtual Promotional Prepaid Visa USD MA",
    sku: 18619,
  },
  {
    country: "Netherlands",
    countryCode: "NL",
    name: "Virtual Promotional Prepaid Visa USD NL",
    sku: 18620,
  },
  {
    country: "Philippines",
    countryCode: "PH",
    name: "Virtual Promotional Prepaid Visa USD PH",
    sku: 18621,
  },
  {
    country: "Poland",
    countryCode: "PL",
    name: "Virtual Promotional Prepaid Visa USD PL",
    sku: 18622,
  },
  {
    country: "Qatar",
    countryCode: "QA",
    name: "Virtual Promotional Prepaid Visa USD QA",
    sku: 18623,
  },
  {
    country: "Saudi Arabia",
    countryCode: "SA",
    name: "Virtual Promotional Prepaid Visa USD SA",
    sku: 18624,
  },
  {
    country: "Spain",
    countryCode: "ES",
    name: "Virtual Promotional Prepaid Visa USD ES",
    sku: 18625,
  },
  {
    country: "Sri Lanka",
    countryCode: "LK",
    name: "Virtual Promotional Prepaid Visa USD LK",
    sku: 18626,
  },
  {
    country: "Taiwan",
    countryCode: "TW",
    name: "Virtual Promotional Prepaid Visa USD TW",
    sku: 18627,
  },
  {
    country: "United Arab Emirates",
    countryCode: "AE",
    name: "Virtual Promotional Prepaid Visa USD AE",
    sku: 18628,
  },
  {
    country: "United Kingdom",
    countryCode: "GB",
    name: "Virtual Promotional Prepaid Visa USD GB",
    sku: 18629,
  },
];
